
name: Auto Promote to Production
on:
  pull_request:
    branches:
      - production
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write

concurrency:
  group: auto-promote
  cancel-in-progress: true

jobs:
  check-pr-from-staging:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'production'
    timeout-minutes: 3
    steps:
      - name: Check PR branch from `staging`
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" == "staging" ]]; then
            echo "OK: PR head branch is 'staging'"
            exit 0
          fi
          echo "ERR: PR head branch is not 'staging'"
          exit 1

      - name: Write comment if PR head branch is not `staging`
        uses: marocchino/sticky-pull-request-comment@v2
        if: success()
        with:
          header: remind-wrong-branch
          delete: true
   
      - name: Write comment if PR head branch is not `staging`
        uses: marocchino/sticky-pull-request-comment@v2
        if: failure()
        with:
          header: remind-wrong-branch
          message: |
            ## 🚫 Pull Request Merge To `production` must be from `staging`

            Hello @${{ github.event.pull_request.user.login }} -san,

            Please create a Pull Request to the `staging` branch and request review there.
            After it got approved, you can create a Pull Request to the `production` branch.
            Thank you for your cooperation. :bow:

            _Recently, we made this change to ensure better stability for BASTION hosts._

  auto-promote-to-production:
    runs-on: ubuntu-latest
    needs: check-pr-from-staging
    permissions: write-all
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'production' && github.event.pull_request.head.ref == 'staging'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      
      - name: Run Danger
        run: |
          export DANGER_GITHUB_API_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          bundle exec danger --fail-on-errors=true
