name: Create PR Release Staging to Production
on:
  push:
    branches:
      - staging
jobs:
  pr-release-stg-to-prod:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Create PR release
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.MY_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: "production"
          GIT_PR_RELEASE_BRANCH_STAGING: "staging"
          GIT_PR_RELEASE_TEMPLATE: .github/git-pr-release.erb
        run: |
          gem install git-pr-release
          git-pr-release --squashed || echo "Done."
