name: Check staging
on:
  pull_request:
    branches:
      - staging
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write

concurrency:
  group: check
  cancel-in-progress: true

jobs:
  check-danger:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'staging'

    container:
      image: ghcr.io/danger/danger:v9.4.2
      options: --user 1001:1001
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug 1
        run: pwd
      
      - name: Debug 2
        run: ls -la .

      - name: Run Danger
        run: |
          bundle exec danger --fail-on-errors=true
